# Generated by Django 3.2.9 on 2021-12-01 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('not_selected', 'Не выбран'), ('man', 'Мужской'), ('woman', 'Женский')], max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.CharField(choices=[('minsk', 'Минск'), ('brest', 'Брест')], max_length=8),
        ),
    ]
