# Generated by Django 3.2.9 on 2021-12-01 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20211201_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('not_selected', 'Не выбран'), ('man', 'Мужской'), ('woman', 'Женский')], max_length=12),
        ),
    ]
