# Generated by Django 3.2.9 on 2021-11-08 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advert', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advert',
            name='city',
        ),
        migrations.AddField(
            model_name='advert',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='advert.city'),
        ),
    ]
