# Generated by Django 3.2.9 on 2021-11-08 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advert', '0003_subcategory_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='advert',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='advert.category'),
        ),
        migrations.AddField(
            model_name='advert',
            name='subcategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='advert.subcategory'),
        ),
    ]
