# Generated by Django 3.2.9 on 2021-11-08 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advert', '0008_alter_advert_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='status',
            field=models.CharField(choices=[('moderation', 'На модерации'), ('active', 'Активные'), ('rejected', 'Отклоненные'), ('inactive', 'Неактивные')], default=('active', 'Активные'), max_length=12),
        ),
    ]
