# Generated by Django 3.2.9 on 2021-12-02 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advert', '0010_alter_advert_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='advert',
            name='status',
            field=models.CharField(choices=[('active', 'Активные'), ('moderation', 'На модерации'), ('rejected', 'Отклоненные'), ('inactive', 'Неактивные')], default='moderation', max_length=12),
        ),
    ]
