# Generated by Django 3.2.9 on 2021-12-02 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advert',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=65, verbose_name='Тема')),
                ('description', models.TextField(max_length=256, verbose_name='Описание')),
            ],
        ),
    ]
