# Generated by Django 3.2.9 on 2021-12-02 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_help_emanil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='help',
            name='emanil',
            field=models.EmailField(max_length=65, verbose_name='Email для свзяи'),
        ),
    ]
